<?php

namespace AppBundle\Repository;

/**
 * FootballTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
