<?php

namespace AppBundle\Repository;

/**
 * FootballLeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballLeagueRepository extends \Doctrine\ORM\EntityRepository
{
}
